FROM postgis/postgis:17-3.5

COPY ./scripts/1_create_schema.sql /docker-entrypoint-initdb.d/1_create_schemas.sql
COPY ./scripts/2_install_baseline_2019.sql /docker-entrypoint-initdb.d/2_install_baseline_2019.sql

# Install wget and clean up apt cache to keep image small
RUN apt-get update && \
    apt-get install -y --no-install-recommends wget unzip && \
    rm -rf /var/lib/apt/lists/*

# Create data directory if it doesn't exist
RUN mkdir -p /data

RUN echo "Downloading Symphony_sv_Polygons.zip..."
RUN wget -P /data/ https://www.havochvatten.se/download/18.7d4f2b16198cd6eed1b4ec71/1756215271664/Symphony_sv_Polygons.zip

# Unpack the zip files
RUN echo "Unpacking Symphony_sv_Polygons.zip..."
RUN unzip -o /data/Symphony_sv_Polygons.zip -d /data/

# Clean up zip files after extraction
RUN echo "Cleaning up zip files..."
RUN rm /data/Symphony_sv_Polygons.zip

RUN echo "Download and extraction complete!"