services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh:ro
    ports:
      - "8080:8080"
      - "9990:9990"
      - "4200:4200"
    depends_on:
      - db
      - ldap
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    environment:
      POSTGRES_DB: symphony
      POSTGRES_USER: symphony
      POSTGRES_PASSWORD: symphony
    ports:
      - "5432:5432"

  ldap:
    image: osixia/openldap:1.5.0
    container_name: dev-ldap
    environment:
      LDAP_ORGANISATION: "Example Org"
      LDAP_DOMAIN: "example.org"
      LDAP_ADMIN_PASSWORD: "admin"
    command: --copy-service
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d
      - ./ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom

volumes:
  ldap-data:
  ldap-config:
