version: '3'
services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - '4200:4200'
      - '8080:8080'
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: symphony
      POSTGRES_USER: symphony
      POSTGRES_PASSWORD: symphony
    ports:
      - '5432:5432'
