-- 1. Reconfigure the Symphony data source after automatic schema creation 

-- Run this script only if you've utilized Hibernates' "hbm2ddl.auto" feature to create the database model from the Entity definitions in the app deployment phase. 
-- Unfortunately, hbm2ddl.auto isn't 100% applicable in MSP-Symphony's case and will by default result in discrepancies.

-- These discrepancies are effectively remedied by this script. 

DO $$
DECLARE
	pgAppAgent varchar := 'symphony';  		-- the configured application database user agent
	calcSliceT varchar;
BEGIN

	ALTER TABLE nationalarea ALTER COLUMN narea_areas TYPE text;
	ALTER TABLE capolygon ALTER COLUMN cap_polygon TYPE text;
	ALTER TABLE compoundcomparison ALTER COLUMN cmp_result TYPE json;
	ALTER TABLE scenarioarea ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
	
	IF NOT EXISTS (SELECT column_name FROM information_schema.columns WHERE table_name = 'capolygon' and column_name = 'pg_polygon') THEN
		PERFORM AddGeometryColumn('symphony', 'capolygon', 'pg_polygon', 4326, 'MULTIPOLYGON', 2);
	END IF;
	
	IF NOT EXISTS (SELECT column_name FROM information_schema.columns WHERE table_name = 'scenarioarea' and column_name = 'polygon') THEN
		PERFORM AddGeometryColumn('symphony', 'scenarioarea', 'polygon', 4326, 'MULTIPOLYGON', 2);
	END IF;
	
	IF NOT EXISTS (SELECT column_name FROM information_schema.columns WHERE table_name = 'reliabilitypartition' and column_name = 'rp_polygon') THEN
		PERFORM AddGeometryColumn('symphony', 'rp_polygon', 'polygon', 4326, 'MULTIPOLYGON', 2);
	END IF;

	SELECT table_type FROM information_schema.tables WHERE table_schema = 'symphony' and table_name = 'calculationresultslice' INTO calcSliceT;
	
	IF NOT calcSliceT = 'VIEW' THEN
		DROP TABLE IF EXISTS calculationresultslice;
		CREATE VIEW calculationresultslice AS
		SELECT cr.cares_id AS id,
		   cr.cares_bver_id AS baselineversion_id,
		   cr.cares_calculationname AS calculationname,
		   cr.cares_timestamp AS "timestamp",
		   cr.cares_owner AS owner,
		   cr.cares_geotiff IS NULL AS ispurged,
		   (((s.changes ->> 'baseChanges'::text)::json) ->> 'PRESSURE'::text) IS NOT NULL
				 OR (((s.changes ->> 'baseChanges'::text)::json) ->> 'ECOSYSTEM'::text) IS NOT NULL
				 OR (( SELECT count(ac.key) AS count
					FROM json_each((s.changes ->> 'areaChanges'::text)::json) ac(key, value)
					WHERE NOT ac.value::text = '{}'::text)) > 0 AS haschanges
		  FROM scenariosnapshot s
			JOIN calculationresult cr ON cr.scenariosnapshot_id = s.id;
	END IF;

	EXECUTE FORMAT ('ALTER VIEW calculationresultslice OWNER TO %s', pgAppAgent);
	EXECUTE FORMAT ('GRANT SELECT ON calculationresultslice TO %s', pgAppAgent);

  EXECUTE format('ALTER DATABASE %I SET search_path TO symphony,public', current_database());

END
$$;
